############################
# --- Required options --- #
############################

title: HTDT MAIN

description: |
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
  labore et dolore magna aliqua. 

author: |
  Organizers: <br>
  Verónica Errasti Díez <br>
  Alexander Felski <br>
  Andreas Fring <br>
  Takano Taira <br>
  Bethan Turner <br>

url-pretty: "hightimeseminar.github.io"
title-on-all-pages: true


###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Register: "register"
  Participants: "participants"
  HTDT Archive: "archive"


#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  youtube: "@GhostlySeminar"


######################################
# --- Visual Customization --- #
######################################

site-css:
  - "/assets/css/custom.css"


#####################################
# --- Build & Engine Options --- #
#####################################

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Standard page defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude unnecessary files from the build
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-sitemap